// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LsruKKWpzpEMfePI9RNclcaNSmcU8DA',
    appId: '1:317551820649:web:8af4e3fff47a4c937387f8',
    messagingSenderId: '317551820649',
    projectId: 'ctse-2b546',
    authDomain: 'ctse-2b546.firebaseapp.com',
    storageBucket: 'ctse-2b546.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-OCEO5srNR_yjaNwmixx7QAb6d9C-vE',
    appId: '1:317551820649:android:07e41b782d2f807a7387f8',
    messagingSenderId: '317551820649',
    projectId: 'ctse-2b546',
    storageBucket: 'ctse-2b546.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgxz3I-wCSwmIb4rJ4YGdIElQz9CHUDs',
    appId: '1:317551820649:ios:d7b4773b8ab284247387f8',
    messagingSenderId: '317551820649',
    projectId: 'ctse-2b546',
    storageBucket: 'ctse-2b546.appspot.com',
    iosClientId: '317551820649-46nvbahj6l43g31pa1ndb8cuhdi8da3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivitySunday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVgxz3I-wCSwmIb4rJ4YGdIElQz9CHUDs',
    appId: '1:317551820649:ios:d7b4773b8ab284247387f8',
    messagingSenderId: '317551820649',
    projectId: 'ctse-2b546',
    storageBucket: 'ctse-2b546.appspot.com',
    iosClientId: '317551820649-46nvbahj6l43g31pa1ndb8cuhdi8da3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivitySunday',
  );
}
